spring:
  mail:
    host: in-v3.mailjet.com
    port: 587
    username:
    password:
    from-address:
    properties:
      mail:
        smtp:
          auth: ture
          starttls:
            enabled: true